### ISSUE TITLE
GetHisCandles returns 404

### ISSUE THREAD

**Issue by lfaoro** [toorop/go-bittrex#17]
the `GetHisCandles()` function seems to be pointing to a dead endpoint: `https://bittrex.com/Market/Pub_GetTickData`

**Comment by mdzor** [comment]
https://github.com/toorop/go-bittrex/pull/21
fixed here

**Comment by AlessandroSanino1994** [comment]
still getting that error

**Comment by mdzor** [comment]
Merged now, btw @AlessandroSanino1994 the two methods are now dead endpoints on Bittrex side. It has been cleaned from go-bittrex in #21.

**Comment by lfaoro** [comment]
fixed? Seems that you just removed the non-working endpoints but also the functionality. How do we get Candles data now?

**Comment by mdzor** [comment]
@lfaoro https://bittrex.com/Home/Api please search for candles here and tell me when you find 👍
