### ISSUE TITLE
GetOrderBook unmarshal error with "buy" or "sell" parameter

### ISSUE THREAD

**Issue by revmen** [toorop/go-bittrex#18]
When executing `bittrex.GetOrderBook("BTC-ETH", "buy", 10)` an unmarshal error occurs:

```json: cannot unmarshal array into Go value of type bittrex.OrderBook {[] []}```

The same thing happens with `"buy`" changed to`"sell"`. It does not occur when set to `"both"`.

If `"both"` is the only valid option, then there's no point in passing it to the function, right?

**Comment by mdzor** [comment]
https://github.com/toorop/go-bittrex/pull/20
fixed here
