### ISSUE TITLE
The depth parameter on GetOrderBook has no effect

### ISSUE THREAD

**Issue by revmen** [toorop/go-bittrex#19]
Regardless of what the depth parameter in `bittrex.GetOrderBook("BTC-ETH", "both", 10)` is set to, the `Buy` and `Sell` slices get thousands of items. The whole book, I assume.

This may be a problem with the Bittrex API, not this library.

**Comment by mdzor** [comment]
Yes it seems coming from Bittrex itself, raised the issue on their slack.
