### ISSUE TITLE
How to calculate % Change ?

### ISSUE THREAD

**Issue by surendrakumar1992** [toorop/go-bittrex#34]
Hello Guys,

I am using getmarketsummary api. 
![image](https://user-images.githubusercontent.com/12594740/31064988-515b9730-a75f-11e7-8e13-c86dceb57cc1.png)

how to calculate % Change from this data?

**Comment by sharpner** [comment]
`(prevDay/LastDay * 100) - 100` 
in your example: 
`((0,01229501 / 0,01349998) * 100) - 100) => -8,926 %`

**Comment by mdmalik** [comment]
Usually a change % is calculated base on the following formula
`( (LastDay-prevDay)*100 ) /prevDay`
if the answer is Negative then a downward growth or else the other way around

`((0.01349998 - 0.01229501) *100) / 0.01349998 => 9.8% `
